import esbuild from 'esbuild';
import { chmod } from 'node:fs/promises';

await esbuild.build({
  banner: {
    js: `/* Generated by esbuild. */
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);`,
  },
  entryPoints: ['src/cli/main.ts'],
  bundle: true,
  format: 'esm',
  platform: 'node',
  target: 'node22',
  outfile: 'dist/focus-flow.mjs',
  sourcemap: false,
  treeShaking: true,
});

await chmod('dist/focus-flow.mjs', 0o755);
